### PR TITLE
Improve README

### PR DESCRIPTION
**Pull request by dfosco**
@brenoc @tamorim @amoreira @bellacorbo Do you enjoy this format with a couple of images for the app and an informal description of features/usage?

### CODE REVIEW

**Comment by brenoc** [comment]
That's good! Just two things:
- The images are too big, maybe let them side by side
- Keep the images in a `docs/` directory instead of the root directory

**Comment by brenoc** [comment]
Oh, and what about the headers: Routes, Areas, Components, like https://github.com/vtex-apps/product-page-wrapper

**Comment by tamorim** [comment]
@dfosco That PanelNav component doesn't do that specified on the README, at least not yet '-'

**Comment by dfosco** [comment]
@brenoc Whoa, they weren't supposed to be this big! Will fix them. About the headers, we should add them even if they're empty for now, yes.

**Comment by dfosco** [comment]
@tamorim It doesn't? But I just tested it — if you change `navType` on `FilterPanel.js` it will pass down the prop to `PanelNav.js` and change the style accordingly. 

I'd say we need an editor for this in the future, though :)

**Comment by brenoc** [comment]
@tamorim the README is missing: https://github.com/vtex-apps/filter-panel/pull/3#issuecomment-161265840

**Comment by tamorim** [comment]
@brenoc I will open a separated issue for this and work on this soon

**Pull request merged**
