### PR TITLE
Remove theme styles

### PR DESCRIPTION
**Pull request by dfosco**
- Remove theme styles
 - Remove `~utils/base` and its references

### CODE REVIEW

**Comment by dfosco** [comment]
@brenoc @tamorim Needs review

**Comment by brenoc** [comment]
LGTM :+1:

**Comment by dfosco** [comment]
@tamorim Can you take a look? I need to have this merged on master and published to the gallery, otherwise I have to keep this app running on my desktop as well.

**Comment by tamorim** [comment]
:zap:

**Pull request merged**
